#ifndef __START_H__
#define __START_H__
#include "mm.h"
#include "common.h"
extern void main(void);
extern void trap_handler();

typedef enum{
    //1 0 RESERVED
    SUPERVISOR_SOFTWARE_INTERRUPT = 1,
    //1 2 RESERVED
    MACHINE_SOFTWARE_INTERRUPT = 3,
    //1 4 RESERVED
    SUPERVISOR_TIMER_INTERRUPT = 5,
    //1 6 RESERVED
    MACHINE_TIMER_INTERRUPT = 7,
    //1 8 RESERVED
    SUPERVISOR_EXTERNAL_INTERRUPT = 9,
    //1 10 RESERVED
    MACHINE_EXTERNAL_INTERRUPT = 11
    //1 12–15 RESERVED
    //1 ≥16 DESIGNATED FOR PLATFORM USE
}interrupt_t;
typedef enum{
    INSTRUCTION_ADDRESS_MISALIGNED = 0,
    INSTRUCTION_ACCESS_FAULT = 1,
    ILLEGAL_INSTRUCTION = 2,
    BREAKPOINT =3,
    LOAD_ADDRESS_MISALIGNED = 4,
    LOAD_ACCESS_FAULT = 5,
    STORE_AMO_ADDRESS_MISALIGNED = 6,
    STORE_AMO_ACCESS_FAULT = 7,
    ENVIRONMENT_CALL_FROM_U_MODE = 8,
    ENVIRONMENT_CALL_FROM_S_MODE = 9,
    //10 RESERVED
    ENVIRONMENT_CALL_FROM_M_MODE = 11,
    INSTRUCTION_PAGE_FAULT = 12,
    LOAD_PAGE_FAULT = 13,
    //14 RESERVED
    STORE_AMO_PAGE_FAULT = 15,
    //16–23 RESERVED
    //24–31 DESIGNATED FOR CUSTOM USE
    //32–47 RESERVED
    //48–63 DESIGNATED FOR CUSTOM USE
    //≥64 RESERVED
} exception_t;

typedef enum{
    PMP_R = (1L << 0),
    PMP_W = (1L << 1),
    PMP_X = (1L << 2),
    PMP_TOR =  (1L << 3),
    PMP_NAPOT = (3L << 3)
}pmp_t;
#endif //__START_H__